/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GardenPageRouteImport } from './routes/gardenPage'
import { Route as AddPlantPageRouteImport } from './routes/addPlantPage'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenPageRoute = GardenPageRouteImport.update({
  id: '/gardenPage',
  path: '/gardenPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPlantPageRoute = AddPlantPageRouteImport.update({
  id: '/addPlantPage',
  path: '/addPlantPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addPlantPage': typeof AddPlantPageRoute
  '/gardenPage': typeof GardenPageRoute
  '/login': typeof LoginRoute
  '/tasks': typeof TasksRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addPlantPage': typeof AddPlantPageRoute
  '/gardenPage': typeof GardenPageRoute
  '/login': typeof LoginRoute
  '/tasks': typeof TasksRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addPlantPage': typeof AddPlantPageRoute
  '/gardenPage': typeof GardenPageRoute
  '/login': typeof LoginRoute
  '/tasks': typeof TasksRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/addPlantPage'
    | '/gardenPage'
    | '/login'
    | '/tasks'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/addPlantPage'
    | '/gardenPage'
    | '/login'
    | '/tasks'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/addPlantPage'
    | '/gardenPage'
    | '/login'
    | '/tasks'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddPlantPageRoute: typeof AddPlantPageRoute
  GardenPageRoute: typeof GardenPageRoute
  LoginRoute: typeof LoginRoute
  TasksRoute: typeof TasksRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gardenPage': {
      id: '/gardenPage'
      path: '/gardenPage'
      fullPath: '/gardenPage'
      preLoaderRoute: typeof GardenPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addPlantPage': {
      id: '/addPlantPage'
      path: '/addPlantPage'
      fullPath: '/addPlantPage'
      preLoaderRoute: typeof AddPlantPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddPlantPageRoute: AddPlantPageRoute,
  GardenPageRoute: GardenPageRoute,
  LoginRoute: LoginRoute,
  TasksRoute: TasksRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
