/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as AddPlantRouteImport } from './routes/addPlant'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPlantRoute = AddPlantRouteImport.update({
  id: '/addPlant',
  path: '/addPlant',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addPlant': typeof AddPlantRoute
  '/garden': typeof GardenRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addPlant': typeof AddPlantRoute
  '/garden': typeof GardenRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addPlant': typeof AddPlantRoute
  '/garden': typeof GardenRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/addPlant'
    | '/garden'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/tasks'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/addPlant'
    | '/garden'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/tasks'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/addPlant'
    | '/garden'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/tasks'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddPlantRoute: typeof AddPlantRoute
  GardenRoute: typeof GardenRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  TasksRoute: typeof TasksRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addPlant': {
      id: '/addPlant'
      path: '/addPlant'
      fullPath: '/addPlant'
      preLoaderRoute: typeof AddPlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddPlantRoute: AddPlantRoute,
  GardenRoute: GardenRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  TasksRoute: TasksRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
